env:
  matrix:
    - LISP=sbcl

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh


script:
  - cl -e '(ql:quickload "alexandria")
           (ql:quickload "fiveam")
           (unless (asdf:test-system "cl-data-gen")
             (uiop:quit 1))'
